export const PUBLIC_AS_OF = "2026-09-02";

const ownershipMonthly = (basis, insurance) => ({
  interestRateAnnual: 0.0666,
  termYears: 30,
  propertyTaxBasisUsd: basis,
  propertyTaxRateAnnual: 0.01,
  insuranceAnnualUsd: insurance,
  hoaMonthlyUsd: 0,
  pmiMonthlyUsd: 0,
  maintenanceRateAnnual: 0.01,
  otherMonthlyUsd: 0,
});

export const exampleEnvelope = {
  schemaVersion: "1.0.0",
  revision: 0,
  updatedAt: "2026-09-02T12:00:00.000Z",
  mode: "private",
  plan: {
    targetMoveDate: "2027-09-01",
    destinationFocus: "both",
    household: { adults: 2, children: 2, dogs: 2 },
    career: {
      status: "researching",
      targetRoles: ["Senior technical program", "Engineering operations", "AI product or solutions"],
      householdNetIncomeMonthlyUsd: 12_000,
      nonHousingSpendMonthlyUsd: 7_000,
    },
    funds: { liquidUsd: 125_000, otherMoveFundsUsd: 25_000, reserveFloorUsd: 40_000 },
    currentHomeSale: {
      estimatedSalePriceUsd: 600_000,
      mortgagePayoffUsd: 350_000,
      sellingCostRate: 0.07,
      prepAndRepairUsd: 12_000,
      sellerFixedClosingUsd: 3_000,
      expectedListDate: "2027-05-15",
      expectedCloseDate: "2027-07-30",
    },
    commonMove: { movingAndTravelUsd: 18_000 },
    scenarios: {
      landBuild: {
        enabled: true,
        landPriceUsd: 200_000,
        buildBaseUsd: 400_000,
        siteWorkUsd: 80_000,
        designPermitDueDiligenceCashOnlyUsd: 40_000,
        buildAndSiteContingencyRate: 0.15,
        downPaymentRate: 0.2,
        loanClosingRate: 0.02,
        prepaidsUsd: 3_000,
        estimatedFinishedValueUsd: 760_000,
        monthly: ownershipMonthly(752_000, 2_400),
        transition: { oneTimeSetupUsd: 5_000, transitionMonthlyUsd: 3_100, transitionMonths: 12 },
      },
      readyHome: {
        enabled: true,
        purchasePriceUsd: 529_000,
        downPaymentRate: 0.2,
        buyerClosingRate: 0.03,
        prepaidsUsd: 3_000,
        monthly: ownershipMonthly(529_000, 1_800),
        transition: { oneTimeSetupUsd: 2_000, transitionMonthlyUsd: 3_500, transitionMonths: 1 },
      },
      fixer: {
        enabled: true,
        purchasePriceUsd: 430_000,
        downPaymentRate: 0.2,
        buyerClosingRate: 0.03,
        prepaidsUsd: 3_000,
        rehabBaseUsd: 90_000,
        rehabContingencyRate: 0.15,
        rehabFinancedUsd: 50_000,
        estimatedPostRehabValueUsd: 560_000,
        monthly: ownershipMonthly(560_000, 1_900),
        transition: { oneTimeSetupUsd: 3_000, transitionMonthlyUsd: 3_100, transitionMonths: 4 },
      },
      rentFirst: {
        enabled: true,
        rentMonthlyUsd: 3_100,
        securityDepositUsd: 3_100,
        firstMonthUsd: 3_100,
        lastMonthUsd: 0,
        petDepositUsd: 800,
        applicationAndMoveInFeesUsd: 400,
        rentersInsuranceMonthlyUsd: 30,
        petRentMonthlyUsd: 100,
        parkingAndOtherMonthlyUsd: 100,
        transition: { oneTimeSetupUsd: 1_500, transitionMonthlyUsd: 0, transitionMonths: 0 },
      },
    },
    selectedFocus: null,
    roadmap: [
      { id: "baseline", phaseId: "foundation", title: "Reconcile income, cash, debts, essentials, credit status, and reserve floor", owner: "both", status: "in-progress", offsetMonths: -12, dueDateOverride: "2026-09-30", scenario: "all", notes: "Use current statements; keep private values out of Git." },
      { id: "family-fit", phaseId: "foundation", title: "Write the family must-haves for schools, dogs, bedrooms, and commute", owner: "both", status: "not-started", offsetMonths: -11, dueDateOverride: "2026-10-15", scenario: "all", notes: "Use address-specific school and pet rules later." },
      { id: "career-tracks", phaseId: "career", title: "Refresh three career tracks and begin weekly role review", owner: "me", status: "not-started", offsetMonths: -11, dueDateOverride: "2026-10-31", scenario: "all", notes: "Intel, NVIDIA, Lam, ASML, Tokyo Electron, Applied Materials, and relevant remote employers." },
      { id: "sale-evidence", phaseId: "sale", title: "Gather payoff, repair scope, two valuation views, and two seller net sheets", owner: "both", status: "not-started", offsetMonths: -9, dueDateOverride: null, scenario: "all", notes: "Do not treat a city median as a home appraisal." },
      { id: "scout", phaseId: "paths", title: "Build matched purchase and dog-compatible rental comparison sets", owner: "partner", status: "not-started", offsetMonths: -8, dueDateOverride: null, scenario: "all", notes: "Compare actual bedroom count, pet terms, school assignment, and commute." },
      { id: "land-gate", phaseId: "paths", title: "Run jurisdiction, access, utility, flood, wetland, septic, and insurance screens", owner: "me", status: "not-started", offsetMonths: -7, dueDateOverride: null, scenario: "land-build", notes: "No land commitment without written feasibility and a rent-first fallback." },
      { id: "career-gate", phaseId: "career", title: "Career Gate 1: offer, credible interview traction, or fallback income plan", owner: "both", status: "not-started", offsetMonths: -6, dueDateOverride: null, scenario: "all", notes: "Keep cash preserved and rent-first open if evidence is weak." },
      { id: "path-focus", phaseId: "decision", title: "Choose a town focus and primary plus backup housing path", owner: "both", status: "not-started", offsetMonths: -5, dueDateOverride: null, scenario: "all", notes: "A focus path is for exploration, not an automated recommendation." },
      { id: "sale-gate", phaseId: "sale", title: "Pass the income, move, current-home exit, and bridge-financing gates", owner: "both", status: "not-started", offsetMonths: -3, dueDateOverride: null, scenario: "all", notes: "List only when the move and overlap plan are financeable." },
      { id: "housing", phaseId: "contract", title: "Complete property or lease diligence and secure Oregon housing", owner: "both", status: "not-started", offsetMonths: -2, dueDateOverride: "2027-07-31", scenario: "all", notes: "Confirm address-specific school, insurance, commute, pet terms, and written fees." },
      { id: "move", phaseId: "move", title: "Physical move window", owner: "both", status: "not-started", offsetMonths: 0, dueDateOverride: "2027-08-21", scenario: "all", notes: "Plan for August 21–27 with backup lodging and storage." },
      { id: "school-ready", phaseId: "settle", title: "Family settled and school-ready milestone", owner: "both", status: "not-started", offsetMonths: 0, dueDateOverride: "2027-09-01", scenario: "all", notes: "This is not the moving-truck date; verify enrollment by actual address." },
    ],
    preferences: { saveOnDevice: false, hideValues: false },
  },
};

export const paths = [
  { key: "landBuild", slug: "land-build", number: "01", title: "Land + build", short: "A two-stage path with the widest timing and feasibility range.", tradeoff: "Highest diligence load: access, utilities, site work, permits, carry, and fallback housing." },
  { key: "readyHome", slug: "ready-home", number: "02", title: "Move-in-ready", short: "Direct ownership when job, sale, financing, and closing dates align.", tradeoff: "Lower project complexity, but property-specific tax, insurance, inspection, and commute still control." },
  { key: "fixer", slug: "fixer", number: "03", title: "Fixer", short: "Ownership plus a defined, inspected improvement program.", tradeoff: "Works only if safely habitable and verified repairs, contingency, financing, and overlap fit the cap." },
  { key: "rentFirst", slug: "rent-first", number: "04", title: "Rent first", short: "A schedule-flexible bridge while worksite or ownership readiness settles.", tradeoff: "Preserves optionality, with pet constraints and the possible cost of moving twice." },
];

export const sources = [
  { group: "Career geography", date: "Q1 2024 data; accessed Sep 2, 2026", label: "City of Hillsboro — Key Industries", url: "https://www.hillsboro-oregon.gov/our-city/departments/economic-development/key-industries", note: "Intel anchors a dense Hillsboro semiconductor ecosystem; headcounts are not current openings." },
  { group: "Career geography", date: "Accessed Sep 2, 2026", label: "Intel — United States locations", url: "https://www.intel.com/content/www/us/en/jobs/locations/united-states.html", note: "Hillsboro is a major R&D and manufacturing site; validate each role's location and work model." },
  { group: "Career geography", date: "Accessed Sep 2, 2026", label: "Lam Research — Locations", url: "https://www.lamresearch.com/company/locations/", note: "Tualatin facilities make the Tigard–Tualatin corridor relevant." },
  { group: "Career geography", date: "Accessed Sep 2, 2026", label: "NVIDIA careers", url: "https://jobs.nvidia.com/", note: "A role-by-role lead only—not a relocation premise." },
  { group: "Housing orientation", date: "July 2026", label: "Redfin — Hillsboro housing market", url: "https://www.redfin.com/city/8712/OR/Hillsboro/housing-market", note: "All-home-type median sale price: about $529,235; not a budget or appraisal." },
  { group: "Housing orientation", date: "July 2026", label: "Redfin — Tigard housing market", url: "https://www.redfin.com/city/18733/OR/Tigard/housing-market", note: "All-home-type median sale price: about $599,675; not a budget or appraisal." },
  { group: "Rent orientation", date: "Aug 31, 2026", label: "Zillow Rental Manager — Hillsboro", url: "https://www.zillow.com/rental-manager/market-trends/hillsboro-or/", note: "Asking-rent averages: about $2,500 for 3BR and $3,106 for 4BR; replace with matched dog-compatible listings." },
  { group: "Rent orientation", date: "Aug 27, 2026", label: "Zillow Rental Manager — Tigard", url: "https://www.zillow.com/rental-manager/market-trends/tigard-or/", note: "Asking-rent averages: about $2,595 for 3BR and $3,700 for 4BR; replace with matched dog-compatible listings." },
  { group: "Financing", date: "Aug 27, 2026", label: "Freddie Mac — Mortgage rates and affordability", url: "https://myhome.freddiemac.com/buying/mortgage-rates", note: "6.66% national 30-year fixed benchmark; not a quote or forecast." },
  { group: "Financing", date: "Accessed Sep 2, 2026", label: "CFPB — Determine your down payment", url: "https://www.consumerfinance.gov/owning-a-home/prepare/determine-your-down-payment/", note: "Closing-cost orientation; replace with lender Loan Estimates." },
  { group: "Taxes", date: "Accessed Sep 2, 2026", label: "Oregon Department of Revenue — Property tax", url: "https://www.oregon.gov/DOR/programs/property/Pages/personal-property.aspx", note: "Tax depends on assessed value and district rates; sale price is not the tax basis." },
  { group: "Land + build", date: "Accessed Sep 2, 2026", label: "Hillsboro — Permitting rates and fees", url: "https://www.hillsboro-oregon.gov/services/permitting-center/rates-fees", note: "Zoning review, site work, utilities, and system-development charges may apply." },
  { group: "Land + build", date: "Accessed Sep 2, 2026", label: "Tigard — System development charges", url: "https://www.tigard-or.gov/your-government/departments/community-development/permit-center/system-development-charges-sdc", note: "Charges vary by project and update; obtain a 2027 estimate." },
  { group: "Family timing", date: "2027–28 calendar", label: "Hillsboro School District calendar", url: "https://www.hsd.k12.or.us/fs/resource-manager/view/159309f8-0339-4883-8dc3-a066c3b4446f", note: "Supports a separate late-August physical move and Sep 1 school-ready milestone." },
  { group: "Family timing", date: "2027–28 calendar", label: "Tigard-Tualatin School District calendar", url: "https://www.ttsdschools.org/fs/resource-manager/view/f26bea5f-fa9a-4842-b0f3-a13e7b5251b7", note: "School assignment is address-specific; city or mailing address is not enough." },
];
